var express = require('express');
var app = express();
var fs = require('fs');
var path = require('path');
app.set('title', 'View Machine');
app.use(express.logger());
app.use(express.static(path.join(__dirname, 'public')));
app.use(express.static(path.join(__dirname, 'lib' , 'VM', 'dist')));
app.use(express.static(path.join(__dirname, 'lib' , 'VM', 'dist')));
app.use(express.static(path.join(__dirname, 'lib' , 'VM3D')));
var port = process.env.PORT || 3000;
app.listen(port);
console.log('Listening on port ' +  port);